# Generated by Django 4.2.5 on 2023-10-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_customuser_area_customuser_health_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyheaddetails',
            name='isLabTestAdded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='isLabTestReportGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='isSampleCollected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='isLabTestAdded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='isLabTestReportGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='isSampleCollected',
            field=models.BooleanField(default=False),
        ),
    ]
