# Generated by Django 4.2.5 on 2023-10-17 05:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_familyheaddetails_islabtestadded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPathlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_date', models.DateTimeField(auto_now=True)),
                ('LabTestSuggested', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HB', 'HB'), ('CBC', 'CBC'), ('Platelet Count', 'Platelet Count'), ('PT/INR', 'PT/INR'), ('RBS', 'RBS'), ('S. Total Bilirubin', 'S. Total BilirubinB'), ('S. Direct Bilirubin', 'S. Direct Bilirubin'), ('SGPT/ALT', 'SGPT/ALT'), ('SGOT/AST', 'SGOT/AST'), ('Urea / BUN', 'Urea / BUN'), ('S. Creatinine', 'S. Creatinine'), ('ALP', 'ALP'), ('S. Total Proteins', 'S. Total Proteins'), ('S. Albumin', 'S. Albumin'), ('S. Total Calcium', 'S. Total Calcium'), ('S. Uric Acid', 'S. Uric Acid'), ('S. Cholesterol', 'S. Cholesterol'), ('S. Triglycerides ', 'S. Triglycerides '), ('S. HDL (Direct)', 'S. HDL (Direct)'), ('LDL', 'LDL'), ('VLDL', 'VLDL'), ('Amylase', 'Amylase'), ('T3', 'T3'), ('T4', 'T4'), ('HbA1C', 'HbA1C'), ('S. Electrolytes', 'S. Electrolytes'), ('S. TIBC', 'S. TIBC'), ('LDH', 'LDH'), ('Vit. D', 'Vit. D'), ('Vit. B12', 'Vit. B12'), ('Immunoassays', 'Immunoassays')], default=list, max_length=255), blank=True, null=True, size=None)),
                ('PatientSampleTaken', models.BooleanField(default=False)),
                ('LabTestReport', models.JSONField(blank=True, default=dict, null=True)),
                ('doctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('PathLabRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('CentreID', models.CharField(blank=True, max_length=255, null=True)),
                ('bookingVisitID', models.CharField(blank=True, max_length=255, null=True)),
                ('puid', models.CharField(blank=True, max_length=255, null=True)),
                ('patientID', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenRejectedLabTest', models.BooleanField(default=False)),
                ('PathLab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PathLab', to=settings.AUTH_USER_MODEL)),
                ('ReportCheckByDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportCheckByDoctor', to=settings.AUTH_USER_MODEL)),
                ('patientFamilyMember', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientFamilyMember', to='database.familymembers')),
                ('suggested_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_by_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
