# Generated by Django 4.2.5 on 2023-10-17 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_patientpathlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='TertiaryConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terdoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Terspecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('TerdoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('fileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('TerPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TerPatientsConsultancy', to='database.familymembers')),
                ('TerPatientsPathReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TerPatientsPathReport', to='database.patientpathlab')),
                ('TerassignedDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TerassignedDoctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Secdoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Secspecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('SecdoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('SecfileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('SecPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecPatientsConsultancy', to='database.familymembers')),
                ('SecPatientsPathReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecPatientsPathReport', to='database.patientpathlab')),
                ('SecSecassignedDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecassignedDoctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriDoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Prispecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('PridoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('fileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('PriPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PriPatientsConsultancy', to='database.familymembers')),
                ('PriPatientsPathReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PriPatientsPathReport', to='database.patientpathlab')),
                ('PriassignedDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PriassignedDoctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmoConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amodoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Amospecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('AmodoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('AmofileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('AmoPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AmoPatientsConsultancy', to='database.familymembers')),
                ('AmoPatientsPathReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AmoPatientsPathReport', to='database.patientpathlab')),
                ('AmoassignedDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AmoassignedDoctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
