# Generated by Django 4.2.5 on 2023-10-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_dispensary_disphealthpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthpost',
            name='dispensary',
        ),
        migrations.AddField(
            model_name='dispensary',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_dispensary', to='database.ward'),
        ),
    ]
