# Generated by Django 4.2.5 on 2023-10-21 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_healthpost_dispensary_dispensary_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCollegeHealthCareCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCHCName', models.CharField(blank=True, max_length=255, null=True)),
                ('MCHCAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('MCHCContactNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('MCHCType', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalOfficerConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moodoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Mospecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('ModoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('MofileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('MoPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moPatientsConsultancy', to='database.familymembers')),
                ('MoPatientsPathReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moPatientsPathReport', to='database.patientpathlab')),
                ('MooassignedDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moassignedDoctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryHealthCareCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PHCName', models.CharField(blank=True, max_length=255, null=True)),
                ('PHCAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('PHCContactNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('PHCType', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialityHealthCareCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHCName', models.CharField(blank=True, max_length=255, null=True)),
                ('SHCAddress', models.CharField(blank=True, max_length=500, null=True)),
                ('SHCContactNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('SHCType', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testtube',
            name='phlebo',
        ),
        migrations.AddField(
            model_name='area',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_dispensarys_name', to='database.dispensary'),
        ),
        migrations.AddField(
            model_name='primaryconsultancy',
            name='ReferByMedicalOfficer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referByDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondaryconsultancy',
            name='ReferByPrimaryDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReferByPrimaryDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tertiaryconsultancy',
            name='ReferBySecondaryDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReferBySecondaryDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='phlebotomist',
        ),
        migrations.DeleteModel(
            name='TestTube',
        ),
        migrations.AddField(
            model_name='customuser',
            name='MedicalCollegeHealthCare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MedicalCollegeHealthCareDoctor', to='database.medicalcollegehealthcarecenters'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='PrimaryHealthCare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrimaryHealthCareDoctor', to='database.primaryhealthcarecenters'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='SpecialityHealthCare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SpecialityHealthCareDoctor', to='database.specialityhealthcarecenters'),
        ),
    ]
