# Generated by Django 4.2.5 on 2023-10-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_medicalcollegehealthcarecenters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dispensary',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='health_Post',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ward',
        ),
    ]
