# Generated by Django 4.2.5 on 2023-10-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_customuser_dispensary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='health_Post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthpostAmo_mo_name', to='database.healthpost'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wardAmo_mo_name', to='database.ward'),
        ),
        migrations.DeleteModel(
            name='AmoConsultancy',
        ),
    ]
