# Generated by Django 4.2.5 on 2023-10-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_remove_area_areas_area_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='areas',
        ),
    ]
