# Generated by Django 4.2.6 on 2023-10-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_familymembers_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyheaddetails',
            old_name='area',
            new_name='famarea',
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='familyArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familyarea', to='database.area'),
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='familyhealthPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familyhealthpostname', to='database.healthpost'),
        ),
    ]
