# Generated by Django 4.2.5 on 2023-10-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_familymembers_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyheaddetails',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familyheaddeatils_area', to='database.area'),
        ),
    ]
