# Generated by Django 4.2.6 on 2023-10-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_rename_area_familyheaddetails_famarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembers',
            old_name='area',
            new_name='familyarea',
        ),
    ]
