# Generated by Django 4.2.6 on 2023-10-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_rename_area_familymembers_familyarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyheaddetails',
            old_name='famarea',
            new_name='familyarea',
        ),
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='familyArea',
        ),
    ]
