# Generated by Django 4.2.6 on 2023-10-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_rename_famarea_familyheaddetails_familyarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyheaddetails',
            old_name='familyarea',
            new_name='FArea',
        ),
        migrations.RenameField(
            model_name='familymembers',
            old_name='familyarea',
            new_name='area',
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='familyArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familyarea', to='database.area'),
        ),
    ]
