# Generated by Django 4.2.6 on 2023-10-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_rename_familyarea_familyheaddetails_farea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyheaddetails',
            old_name='FArea',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='familyArea',
        ),
    ]
