# Generated by Django 4.2.6 on 2023-10-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_rename_farea_familyheaddetails_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='dispensaryName',
        ),
        migrations.AddField(
            model_name='dispensary',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DispensaryHealthPostAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.dispensary')),
                ('health_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.healthpost')),
            ],
            options={
                'unique_together': {('dispensary', 'health_post')},
            },
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensaryname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='health_posts',
            field=models.ManyToManyField(through='database.DispensaryHealthPostAssociation', to='database.healthpost'),
        ),
    ]
