# Generated by Django 4.2.6 on 2023-10-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_remove_dispensary_dispensaryname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialityHealthCareCenters',
            new_name='HealthCareCenters',
        ),
        migrations.AlterUniqueTogether(
            name='dispensaryhealthpostassociation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dispensaryhealthpostassociation',
            name='dispensary',
        ),
        migrations.RemoveField(
            model_name='dispensaryhealthpostassociation',
            name='health_post',
        ),
        migrations.RenameField(
            model_name='healthcarecenters',
            old_name='SHCAddress',
            new_name='HhealthcareAddress',
        ),
        migrations.RenameField(
            model_name='healthcarecenters',
            old_name='SHCContactNumber',
            new_name='healthCareContactNumber',
        ),
        migrations.RenameField(
            model_name='healthcarecenters',
            old_name='SHCName',
            new_name='healthCareName',
        ),
        migrations.RenameField(
            model_name='healthcarecenters',
            old_name='SHCType',
            new_name='healthCareType',
        ),
        migrations.RemoveField(
            model_name='area',
            name='dispensary',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='MedicalCollegeHealthCare',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='PrimaryHealthCare',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='SpecialityHealthCare',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dispensary',
        ),
        migrations.AddField(
            model_name='customuser',
            name='HealthCareFacility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrimaryHealthCareDoctor', to='database.healthcarecenters'),
        ),
        migrations.DeleteModel(
            name='dispensary',
        ),
        migrations.DeleteModel(
            name='DispensaryHealthPostAssociation',
        ),
        migrations.DeleteModel(
            name='MedicalCollegeHealthCareCenters',
        ),
        migrations.DeleteModel(
            name='PrimaryHealthCareCenters',
        ),
    ]
