# Generated by Django 4.2.6 on 2023-10-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_rename_specialityhealthcarecenters_healthcarecenters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='HealthCareFacility',
        ),
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='familyhealthPost',
        ),
        migrations.AddField(
            model_name='customuser',
            name='HealthCareCenters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HealthCareDoctor', to='database.healthcarecenters'),
        ),
        migrations.AlterField(
            model_name='familyheaddetails',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familyheaddeatils_area', to='database.area'),
        ),
        migrations.CreateModel(
            name='dispensary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensaryName', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_dispensary', to='database.ward')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_dispensarys_name', to='database.dispensary'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensary_name', to='database.dispensary'),
        ),
    ]
