# Generated by Django 4.2.5 on 2023-10-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_familyheaddetails_area'),
        ('database', '0022_remove_customuser_healthcarefacility_and_more'),
    ]

    operations = [
    ]
