# Generated by Django 4.2.6 on 2023-11-01 17:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_merge_20231030_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcarecenters',
            name='healthCareType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PHCC', 'Primary Health Care Center'), ('SHCC', 'Secondary Health Care Center'), ('THCC', 'Tertiary Health Care Center')], default=list, max_length=255), blank=True, null=True, size=None),
        ),
    ]
