# Generated by Django 4.2.6 on 2023-11-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_merge_20231030_1551'),
        ('database', '0025_medicalofficerconsultancy_referedtoprimaryconsultancy_and_more'),
    ]

    operations = [
    ]
