# Generated by Django 4.2.5 on 2023-11-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_merge_20231103_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyheaddetails',
            name='pendingMembers',
            field=models.IntegerField(default=0),
        ),
    ]
