# Generated by Django 4.2.5 on 2023-11-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_familyheaddetails_pendingmembers'),
        ('database', '0028_labtests_description'),
    ]

    operations = [
    ]
