# Generated by Django 4.2.5 on 2023-11-07 09:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_labtests_testid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtests',
            name='testId',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientpathlab',
            name='LabTestSuggested',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=255), blank=True, null=True, size=None),
        ),
    ]
