# Generated by Django 4.2.5 on 2023-11-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_alter_labtests_testid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPathLabReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfResult', models.FileField(upload_to='patientPathLabResults')),
                ('jsonResult', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patientPathLab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPathLabReports', to='database.patientpathlab')),
            ],
        ),
    ]
