# Generated by Django 4.2.5 on 2023-11-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_patientpathlabreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='generalStatus',
            field=models.CharField(default='Survey Completed', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientpathlabreports',
            name='jsonResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientpathlabreports',
            name='pdfResult',
            field=models.FileField(blank=True, null=True, upload_to='patientPathLabResults'),
        ),
    ]
