# Generated by Django 4.2.5 on 2023-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_remove_patientpathlab_labtestsuggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpathlab',
            name='LabTestSuggested',
            field=models.JSONField(default=dict),
        ),
    ]
