# Generated by Django 4.2.5 on 2023-11-21 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_patientpathlab_labtestsuggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyheaddetails',
            name='ASHA_CHV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ASHA_CHV_family_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='ASHA_CHV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ASHA_CHV_family_Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
