# Generated by Django 4.2.5 on 2023-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_familyheaddetails_asha_chv_familymembers_asha_chv'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='cbacRequired',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
