# Generated by Django 4.2.5 on 2023-11-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_patientpathlabreports_pdfurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpathlabreports',
            name='pdfResult',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='patientPathLabResults'),
        ),
    ]
