# Generated by Django 4.2.5 on 2023-11-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_alter_patientpathlabreports_pdfresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='created_datetime',
        ),
    ]
