# Generated by Django 4.2.5 on 2023-11-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_remove_familyheaddetails_created_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='refereloptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=255, null=True)),
                ('createdDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='familymembers',
            name='referels',
            field=models.ManyToManyField(blank=True, related_name='refereloptions_related', to='database.refereloptions'),
        ),
    ]
