# Generated by Django 4.2.5 on 2023-12-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_refereloptions_familymembers_referels'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='deniedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
