# Generated by Django 4.2.5 on 2023-12-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_alter_familymembers_bloodcollectionlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='aadharCard',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='cbacRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='mobileNo',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
