# Generated by Django 4.2.5 on 2023-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='vulnerableOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=255, null=True)),
                ('createdDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='familymembers',
            name='vulnerable_reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='vulnerable_choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='vulnerability_choices', to='database.vulnerableoptions'),
        ),
    ]
