# Generated by Django 4.2.5 on 2023-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_vulnerableoptions_familymembers_vulnerable_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='vulnerable_choices',
            field=models.ManyToManyField(blank=True, related_name='vulnerability_choices', to='database.vulnerableoptions'),
        ),
    ]
