# Generated by Django 4.2.5 on 2023-12-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0049_rename_supervisor_customuser_careated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='careated_by',
            new_name='created_by',
        ),
    ]
