# Generated by Django 4.2.5 on 2023-12-13 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('database', '0050_rename_careated_by_customuser_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApprovalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField()),
                ('approve_date', models.DateTimeField()),
                ('new_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_new_Group', to='auth.group')),
                ('old_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_old_Group', to='auth.group')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserRequester', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserApprovalRecords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
