# Generated by Django 4.2.5 on 2023-12-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_userapprovalrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapprovalrecords',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userapprovalrecords',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
