# Generated by Django 4.2.5 on 2023-12-20 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_alter_userapprovalrecords_approve_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ANM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ANM_Id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='bloodCollectionLocation',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Center', 'Center'), ('Denied', 'Denied'), ('Not Required', 'Not Required'), ('Individual Itself', 'Individual Itself'), ('AMO', 'AMO')], max_length=20, null=True),
        ),
    ]
