# Generated by Django 4.2.5 on 2024-01-02 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_customuser_anm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='userSections',
            field=models.ManyToManyField(blank=True, related_name='multiple_Section', to='database.section'),
        ),
    ]
