# Generated by Django 4.2.5 on 2024-01-06 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_patientspathlabrecords_alter_area_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Mother ', 'Mother '), ('Father', 'Father'), ('Spouse', 'Spouse'), ('Daughter', 'Daughter'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Grandmother ', 'Grandmother '), ('Grandfather ', 'Grandfather '), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Nephew', 'Nephew'), ('Niece', 'Niece')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='CentreID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='LabTestReport',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='LabTestSuggested',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='PathLab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PathLab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='PathLabRemarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='PatientSampleTaken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='ReportCheckByDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportCheckByDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='bookingVisitID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='citizenRejectedLabTest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='doctorRemarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='patientFamilyMember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientFamilyMember', to='database.familymembers'),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='patientID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='puid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='suggested_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_by_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='suggested_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='areas',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
