# Generated by Django 4.2.5 on 2024-01-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_patientspathlabrecords_centreid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientPathlab',
        ),
    ]
