# Generated by Django 4.2.5 on 2024-01-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_delete_patientpathlab'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Mother ', 'Mother '), ('Father', 'Father'), ('Spouse', 'Spouse'), ('Daughter', 'Daughter'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Grandmother ', 'Grandmother '), ('Grandfather ', 'Grandfather '), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Nephew', 'Nephew'), ('Niece', 'Niece')], max_length=100, null=True),
        ),
    ]
