# Generated by Django 4.2.5 on 2024-01-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_familymembers_relationship_and_more'),
        ('database', '0058_familymembers_relationship'),
    ]

    operations = [
    ]
