# Generated by Django 4.2.5 on 2024-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_remove_patientspathlabrecords_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='transactionid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
