# Generated by Django 4.2.5 on 2024-01-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0063_patientspathlabrecords_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientspathlabrecords',
            name='centreName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
