# Generated by Django 4.2.5 on 2024-01-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0064_patientspathlabrecords_centrename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientspathlabrecords',
            old_name='centreName',
            new_name='centerName',
        ),
    ]
