# Generated by Django 4.2.5 on 2024-01-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_rename_centrename_patientspathlabrecords_centername'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='isAbhaCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Mother', 'Mother'), ('Father', 'Father'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Nephew', 'Nephew'), ('Niece', 'Niece')], max_length=100, null=True),
        ),
    ]
