# Generated by Django 4.2.5 on 2024-02-19 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_familymembers_isabhacreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='caseCompletion',
            field=models.CharField(blank=True, choices=[('Referral', 'Referral'), ('Diagnosis/Treatment', 'Diagnosis/Treatment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisorId', to=settings.AUTH_USER_MODEL),
        ),
    ]
