# Generated by Django 4.2.5 on 2024-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0068_alter_familymembers_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='is_hypertensive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Mother', 'Mother'), ('Father', 'Father'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Sibling', 'Sibling'), ('SonInLaw', 'SonInLaw'), ('DaughterInLaw', 'DaughterInLaw')], max_length=100, null=True),
        ),
    ]
