{
    "part_a": [
        {"answer": [], "question": "What is your age? (complete years)"},
        {
            "answer": [],
            "question": "Do you smoke or consume smokeless product such as gutka or khaini?",
        },
        {"answer": [], "question": "Do you consume alcohol daily"},
        {"answer": [], "question": "Measurement of waist in cm"},
        {
            "answer": [],
            "question": "Do you undertake any physical activities for minimum of 150 minutes in a week (Daily min 30 minutes per day- 5 days a week)",
        },
        {
            "answer": [],
            "question": "Do you have a family history (any one of your parent or sibling ) of high BP, DM and Heart Disease",
        },
    ],
    "part_b": [
        {"answer": [], "question": "Shortness of Breath (Difficulty in Breathing)"},
        {"answer": [], "question": "Cough lasting more than 2 weeks"},
        {"answer": [], "question": "Blood in sputum"},
        {"answer": [], "question": "Fever for more than 2 weeks"},
        {"answer": [], "question": "Loss of weight"},
        {"answer": [], "question": "Night sweat"},
        {"answer": [], "question": "Are you currently taking Anti TB Drugs"},
        {"answer": [], "question": "Anyone in family currently suffering from TB"},
        {"answer": [], "question": "History of TB"},
        {"answer": [], "question": "Recurrent ulceration on palms or sole"},
        {"answer": [], "question": "Recurrent Tingling on palms or sole"},
        {"answer": [], "question": "Cloudy or blurred vision"},
        {"answer": [], "question": "Difficulty in Reading"},
        {"answer": [], "question": "Pain in eyes lasting for more than a week"},
        {"answer": [], "question": "Redness in eyes lasting for more than a week"},
        {"answer": [], "question": "Difficulty in hearing"},
        {"answer": [], "question": "History of convulsions – fits"},
        {"answer": [], "question": "Difficulty in opening Mouth"},
        {"answer": [], "question": "Any ulcer in mouth that has not healed in 2 weeks"},
        {
            "answer": [],
            "question": "Any growth / mass in mouth that has not healed in 2 weeks",
        },
        {
            "answer": [],
            "question": "Any white or red patch in mouth that has not healed in 2 weeks",
        },
        {"answer": [], "question": "Pain while chewing"},
        {"answer": [], "question": "Any change in tone of your voice"},
        {
            "answer": [],
            "question": "Any hypopigmented patch or discoloured lesions in oral cavity with loss of sensation",
        },
        {"answer": [], "question": "Any thickened skin"},
        {"answer": [], "question": "Any nodules on skin"},
        {"answer": [], "question": "Recurrent numbness on palms or sole"},
        {"answer": [], "question": "Clawing of fingers of hands and feet"},
        {"answer": [], "question": "Tingling_and_numbness_in_hands_and_feet"},
        {"answer": [], "question": "Inability to close eyelids completely"},
        {"answer": [], "question": "Difficulty in holding objects in hands"},
        {
            "answer": [],
            "question": "Weakness in feet that causes difficulty in walking",
        },
        {"answer": [], "question": "Lump in breast"},
        {"answer": [], "question": "Blood stained discharge from the nipple"},
        {"answer": [], "question": "Changes in shape and size of breast"},
        {"answer": [], "question": "Bleeding between periods"},
        {"answer": [], "question": "Bleeding after menopause"},
        {"answer": [], "question": "Bleeding after intercourse"},
        {"answer": [], "question": "Foul smelling vaginal discharge"},
        {"answer": [], "question": "Feeling unsteady while standing or walking"},
        {
            "answer": [],
            "question": "Suffering from any physical disability that restricts movement",
        },
        {
            "answer": [],
            "question": "Needing help from others to perform everyday activities such as eating , getting dressed, grooming , bathing, walking, or using toilet",
        },
        {
            "answer": [],
            "question": "Forgetting names of your near ones or your home address",
        },
    ],
    "part_c": [
        {"answer": [], "question": "Type of Fuel used for cooking"},
        {"answer": [], "question": "Occupational exposure"},
    ],
    "part_d": [
        {"answer": [], "question": "Little interest of pleasure in doing things ?"},
        {"answer": [], "question": "Feeling low/down,depressed or hopeless/sadness ?"},
    ],
    "part_e": [
        {"answer": [], "question": "Fever"},
        {"answer": [], "question": "With Chills"},
        {"answer": [], "question": "With Rash"},
        {"answer": [], "question": "With Bleeding"},
        {"answer": [], "question": "With Altered Sensorium"},
        {"answer": [], "question": "Waddling in water"},
        {
            "answer": [],
            "question": "Exposure to domestic animal like cattle / Dog / Cat / Pig / Rodent",
        },
        {"answer": [], "question": "Loose Motion"},
        {"answer": [], "question": "With Blood"},
        {"answer": [], "question": "Vomitting"},
        {
            "answer": [],
            "question": "Eating outside / uncovered food / drinking contaminated water",
        },
        {"answer": [], "question": "Animal Bite(cattle/dogs/cats)"},
        {"answer": [], "question": "Snake Bite"},
        {
            "answer": [],
            "question": "History of amputation due to diabetes complication",
        },
    ],
}
