{
    "part_a": [
        {"answer": ["30_39_year"], "question": "What_is_your_age_completeyears"},
        {
            "answer": ["Used_to_consume_in_the_past_Sometimes_now"],
            "question": "Do_you_smoke_or_consume_smokeless_products_such_as_gutka_or_khaini",
        },
        {"answer": [], "question": "Do_you_consume_alcohol_daily"},
        {"answer": [], "question": "Measurement_of_waist_in_cm"},
        {
            "answer": [],
            "question": "Do_you_undertake_any_physical_activities_for_minimum_of__minutes_in_a_week",
        },
        {
            "answer": [],
            "question": "Do_you_have_a_family_history_any_one_of_your_parents_or_siblings_of_high_blood_pressure_diabetes_and_heart_disease",
        },
    ],
    "part_b": [
        {"answer": ["Yes"], "question": "Shortness_of_breath_difficulty_breathing"},
        {"answer": ["Yes"], "question": "Coughing_more_than__weeks"},
        {"answer": [], "question": "Blood_in_sputum"},
        {"answer": [], "question": "Fever_for_more_than__weeks"},
        {"answer": [], "question": "Loss_of_weight"},
        {"answer": [], "question": "Night_Sweats"},
        {"answer": [], "question": "Are_you_currently_taking_anti_TB_drugs"},
        {"answer": [], "question": "Anyone_in_family_currently_suffering_from_TB"},
        {"answer": [], "question": "History_of_TB"},
        {"answer": [], "question": "Recurrent_ulceration_on_palms_or_sole"},
        {"answer": [], "question": "Recurrent_Tingling_on_palms_or_sole"},
        {"answer": [], "question": "Cloudy_or_blurred_vision"},
        {"answer": [], "question": "Difficulty_in_reading"},
        {"answer": [], "question": "Pain_in_eyes_lasting_for_more_than_a_week"},
        {"answer": [], "question": "Redness_in_eyes_lasting_for_more_than_a_week"},
        {"answer": [], "question": "Difficulty_in_hearing"},
        {"answer": [], "question": "History_of_convulsions__fits"},
        {"answer": [], "question": "Difficulty_in_opening_Mouth"},
        {"answer": [], "question": "Any_ulcer_in_mouth_that_has_not_healed_in__week"},
        {
            "answer": [],
            "question": "Any_growth__mass_in_mouth_that_has_not_healed_in__weeks",
        },
        {
            "answer": [],
            "question": "Any_white_or_red_patch_in_mouth_that_has_not_healed_in__weeks",
        },
        {"answer": [], "question": "Pain_while_chewing"},
        {"answer": [], "question": "Any_change_in_tone_of_your_voice"},
        {
            "answer": [],
            "question": "Any_hypo_pigmented_patch_in_oral_cavity_or_discolored_lesions_with_loss_of_sensation",
        },
        {"answer": [], "question": "Any_thickened_skin"},
        {"answer": [], "question": "Any_nodules_on_skin"},
        {"answer": [], "question": "recurrent_numbness_on_palms_or_sole"},
        {"answer": [], "question": "clawing_of_fingers_of_hands_and_feet"},
        {"answer": [], "question": "tingling_and_numbness_in_hands_and_feet"},
        {"answer": [], "question": "inability_to_close_eyelids_completely"},
        {"answer": [], "question": "difficulty_in_holding_objects_in_hands"},
        {
            "answer": [],
            "question": "weakness_in_feet_that_causes_difficulty_in_walking",
        },
        {"answer": [], "question": "Lump_in_the_breast"},
        {"answer": [], "question": "Blood_stained_discharge_from_the_nipple"},
        {"answer": [], "question": "Change_in_shape_and_size_of_breast"},
        {"answer": [], "question": "Bleeding_between_periods"},
        {"answer": [], "question": "Bleeding_after_menopause"},
        {"answer": [], "question": "Bleeding_after_intercourse"},
        {"answer": [], "question": "Foul_smelling_vaginal_discharge"},
        {"answer": [], "question": "Do_you_feel_unsteady_while_standing_or_walking"},
        {
            "answer": [],
            "question": "Impairment_of_movement_if_suffering_from_physical_disability",
        },
        {
            "answer": [],
            "question": "Do_you_need_help_from_others_to_perform_daily_activities_such_as_eating_dressing_dressing_bathing_walking_or_using_the_toilet",
        },
        {"answer": [], "question": "Forgetting_your_home_address_or_household_names"},
    ],
    "part_c": [
        {
            "answer": ["Firewood", "Crop_Residue", "Cow_dung_cake"],
            "question": "Type_of_Fuel_used_for_cooking",
        },
        {
            "answer": ["Crop_residue_burning", "burning_of_garbage_leaves"],
            "question": "Occupational_exposure",
        },
    ],
    "part_d": [
        {
            "answer": ["Not_at_all"],
            "question": "Little_interest_of_pleasure_in_doing_things",
        },
        {"answer": ["Not_at_all"], "question": "Feeling_down_depressed_or_hopeless"},
    ],
    "part_e": [
        {"answer": ["Less_than__days"], "question": "Fever"},
        {"answer": ["Yes"], "question": "With_Chills"},
        {"answer": ["Yes"], "question": "With_Rash"},
        {"answer": [], "question": "with_Bleeding"},
        {"answer": [], "question": "with_Altered_Sensorium"},
        {"answer": [], "question": "Waddling_in_water"},
        {"answer": [],"question": "Exposure_to_domestic_animal_like_cattle__Dog__Cat__Pig__Rodent",},
        {"answer": [], "question": "Loose_Motion"},
        {"answer": [], "question": "With_Blood"},
        {"answer": [], "question": "Vomitting"},
        {"answer": [],"question": "Eating_outside__uncovered_food__drinking_contaminated_water",},
        {"answer": [], "question": "Animal_Bite"},
        {"answer": [], "question": "Snake_Bite"},
        {"answer": [],"question": "history of amputation due to diabetes complication",
        },
    ],
}
